#!/bin/csh
#module purge
#module load java-tig
#module load ant

if ( $#argv == 0  ) then
  echo "specify a source."
else
  setenv ANT_HOME /usr/share/ant/
  java -Xmx10G -agentlib:jdwp=transport=dt_socket,address=localhost:9009,server=y,suspend=y -classpath ${ANT_HOME}/lib/ant-launcher.jar -Dant.home=${ANT_HOME} -Dant.library.dir=${ANT_HOME}/lib org.apache.tools.ant.launch.Launcher -cp "" -Dsource=$argv[1]

endif
